version: '3.9'

services:
  db:
    image: mysql:8
    container_name: itspp_labs_db
    mem_limit: 1024m
    restart: always
    environment:
      MYSQL_DATABASE: itspp_labs_db
      MYSQL_USER: nodeUser
      MYSQL_PASSWORD: itspp
      MYSQL_ROOT_PASSWORD: itspp
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    volumes:
      - itspp_labs_db_data:/var/lib/mysql
volumes:
  itspp_labs_db_data:
