version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: ./dockerfile.server
    ports:
      - "2000:3000"
    volumes:
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: ./dockerfile.client
    ports:
      - "3173:5173"
    volumes:
      - ./client:/app
