FROM node:lts-bullseye-slim

RUN mkdir /app
WORKDIR /app

# Switch to the root user
USER root

# Install ca-certificates
RUN apt update && apt install -y ca-certificates

COPY ./package*.json ./
RUN npm install
RUN npx prisma generate


CMD [ -d "node_modules" ] && npm run dev || npm ci && npm run dev